Fix warning when gpgcheck return code is >2
If gpgcheck ever returns a code larger than 2, reposync will fail with:
(...)
    my.logger.warning('Removing %s due to failed signature check: %s' % rpmfn)
TypeError: not enough arguments for format string